# Generated by Django 4.1.2 on 2022-11-05 19:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painrecord", "0001_painrecord_model_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painrecord",
            name="pain_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="painrecord",
            name="pain_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
