# Generated by Django 4.1.2 on 2022-11-06 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("painrecord", "0002_alter_painrecord_pain_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pain_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
