# Generated by Django 4.1.2 on 2022-11-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("painrecord", "0003_added_related_name_for_user_pain_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="painrecord",
            options={"ordering": ["-created_datetime"]},
        ),
    ]
